app/flux.1/depth_canny/assets/description.html, app/flux.1/depth_canny/assets/style.css, app/flux.1/depth_canny/run_gradio.py, app/flux.1/depth_canny/utils.py, app/flux.1/depth_canny/vars.py, app/flux.1/fill/assets/description.html, app/flux.1/fill/assets/style.css, app/flux.1/fill/run_gradio.py, app/flux.1/fill/utils.py, app/flux.1/fill/vars.py
This PR includes INT4 demo for:
- Flux.1-canny-dev
- Flux.1-depth-dev
- Flux.1-fill-dev
=> Add demo for Flux.1 canny, depth and fill

comfyui/nodes/models/flux.py
在cpu_offload项中增加auto选项，根据物理显存是否大于14G自动enable/disable该功能。
=> Auto CPU Offload in flux.py: 在cpu_offload项中增加auto选项

.github/workflows/auto-merge-main-into-dev.yml, .github/workflows/sync-to-private.yml
=> [Dont Sync] chore: add workflows to auto-merge main into dev and sync with private repo

src/FluxModel.cpp
=> fix: support for transformer block indices > 19 in forward_layer (FluxModel.cpp)

.github/workflows/auto-merge-main-into-dev.yml, .github/workflows/sync-to-private.yml
=> [Dont Sync] chore: fix the authors of the sync commit

nunchaku/models/transformers/transformer_flux.py, src/FluxModel.cpp
Resolved the issue identified in #297.
=> fix: fix the typo in FluxModel.cpp as in #297

README.md, docs/faq.md
=> docs: add faq

README_ZH.md
=> [docs] update README_ZH.md

.github/workflows/close_inactive_issues.yaml
=> [Dont Sync] chore: lower inactivity threshold from 60 to 30

.github/workflows/close_inactive_issues.yaml
=> chore: increase inactivity threshold from 30 to 60

.github/workflows/lint.yaml
=> chore: update the lint workflow

nunchaku/lora/flux/diffusers_converter.py, tests/flux/test_flux_teacache.py, tests/flux/test_multiple_batch.py
=> test: use CPU offload to save GPU memory in multi-batch test

nunchaku/caching/utils.py
Fix Controlnet-Pro 2
https://github.com/mit-han-lab/ComfyUI-nunchaku/issues/142
https://github.com/mit-han-lab/ComfyUI-nunchaku/issues/157
=> fix: fix stack error to enable Controlnet-Pro-2 working

nunchaku/caching/utils.py
Fix: Resolve a bug in FBCache that appears when ControlNet modules are enabled.
=> fix: FBCache with ControlNet

app/flux.1/sketch/run_gradio.py
Fix the pix2pix-turbo demo in the latest gradio.
=> fix: fix the pix2pix-turbo demo

app/flux.1/sketch/run_gradio.py, examples/flux.1-dev-pulid.py, nunchaku/caching/utils.py, nunchaku/lora/flux/compose.py, nunchaku/lora/flux/diffusers_converter.py, nunchaku/lora/flux/nunchaku_converter.py, nunchaku/models/transformers/transformer_flux.py, tests/flux/test_flux_schnell.py, tests/flux/test_flux_teacache.py, tests/flux/test_lora_reset.py, tests/flux/test_multiple_batch.py, tests/utils.py
* Fix FP8 LoRA and LoRA reset.
* Fix the stack error in ControlNet-Union-Pro2.
* Fix the FBCache with ControlNet.
=> release: v0.3.0dev1 pre-release

nunchaku/__version__.py, nunchaku/caching/utils.py
Fix the ControlNet argument error that #360 introduced. Also, update the version number to 0.3.0.dev2.
=> fix: fix the controlnet argument errors

nunchaku/caching/utils.py
I fixed an issue that FBCache wasn't being applied to SANA.
=> fix : Sana + FBCache

.github/workflows/test_ampere.yaml, .github/workflows/test_blackwell.yaml, scripts/build_all_windows_wheels.cmd, tests/flux/test_flux_schnell.py, tests/flux/test_flux_tools.py, tests/flux/test_lora_reset.py
=> chore: add ComfyUI tests

.github/workflows/clean-nightly-releases.yaml, .github/workflows/nightly-build.yaml
=> chore: add nightly linux wheel build

.github/workflows/win-build.yaml
=> chore: debugging the windows build

debug/flux.1-fill-dev16.py, debug/flux.1-fill-dev4.py, debug/get_image_and_mask.py, debug/split_lora.py, nunchaku/lora/flux/diffusers_converter.py, tests/flux/test_flux_teacache.py
=> fix: convert the unet state_dict to PeFT one to fix the removal LoRA

.github/workflows/clean-nightly-releases.yaml, .github/workflows/test-ampere.yaml, .github/workflows/test-blackwell.yaml
=> chore: fix the workflow to clean nightly wheels

.github/workflows/sync-hf-to-ms.yaml, scripts/sync_hf_to_ms.py
=> chore: fix the hf2ms ci

.github/workflows/nightly-build.yaml, .github/workflows/release-build.yaml, scripts/build_linux_wheel_torch2.8.sh, scripts/build_windows_wheel_torch2.8.cmd
=> chore: support building torch2.8 wheels

nunchaku/lora/flux/compose.py
=> fix: handling single nunchaku LoRA composition

nunchaku/csrc/flux.h, nunchaku/models/pulid/eva_clip/factory.py, nunchaku/models/transformers/transformer_flux.py, nunchaku/pipeline/pipeline_flux_pulid.py, src/FluxModel.cpp
When the EVA CLIP config is not found, I use the built-in JSON parameters instead.The issue of repeated model downloads has been resolved, and the model path specified by ComfyUI will be faithfully used.
=> fix: upgrade pulid to 0.9.1

.github/workflows/test-ampere.yaml, .github/workflows/test-blackwell.yaml
=> chore: use diffusers 0.35 for kontext tests

.github/workflows/build-docs.yaml
=> chore: add build docs workflow

.github/workflows/build-docs.yaml
=> chore: fix the build-docs workflow

.github/workflows/pr-test.yaml
=> chore: better pr-test

README.md, README_ZH.md, examples/flux.1-krea-dev.py
=> feat: support flux.1-krea-dev

nunchaku/caching/diffusers_adapters/flux.py
=> fix: re-enable transformer caching in apply_cache_on_pipe

.github/workflows/nightly-build.yaml, .github/workflows/release-build.yaml
Expect to use cuda 12.8 for torch 2.8, updated the error in windows script
And also sync release build workflow with nightly build workflow
=> chore: fix workflow for torch 2.8

.github/workflows/pr-test.yaml, .github/workflows/release-build.yaml
=> chore: support torch 2.9 uploading wheel to hf

README.md, README_ZH.md, examples/v1/qwen-image-lightning.py
=> feat: support lightning Qwen-Image models

.github/workflows/nightly-build.yaml, .github/workflows/release-build.yaml, scripts/build_all_dockers.sh, scripts/build_all_linux_wheels.sh, scripts/build_all_windows_wheels.cmd
[add support for python 3.13](https://github.com/nunchaku-tech/nunchaku/issues/607)
update yamls and  bash scripts
=> feat: add support for python 3.13

nunchaku/models/transformers/transformer_qwenimage.py, nunchaku/models/utils.py
=> feat: simplify the implementation of the async offloading and support ComfyUI offloading

.github/pull_request_template.md, .github/workflows/build-docs.yaml, README.md, nunchaku/__version__.py, pyproject.toml
=> chore: release nunchaku v1.0.0

examples/v1/qwen-image-controlnet.py, nunchaku/models/transformers/transformer_qwenimage.py
Add the controlnet support for Qwenimage. 
Controlnet model was from [InstantX](https://huggingface.co/InstantX/Qwen-Image-ControlNet-Union).
The example script uses a patched Diffusers QwenImageControlNetPipeline (which had a wrong device type when using cpu offload).
=> feat: support controlnet for qwenimagemodel

README.md, docs/source/links/huggingface.txt, docs/source/usage/qwen-image-edit.rst, examples/v1/qwen-image-edit-2509.py, pyproject.toml
=> feat: support Qwen-Image-Edit-2509
